//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETL.ServicesWeb.Authentification {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://astus.com/services/2010/11", ConfigurationName="Authentification.AuthorizationContract")]
    internal interface AuthorizationContract {
        
        // CODEGEN : La génération du contrat de message depuis l'espace de noms d'une partie du message http://astus.com/service/2010/11 ne correspond pas à la valeur par défaut (http://astus.com/services/2010/11)
        [System.ServiceModel.OperationContractAttribute(Action="http://astus.com/service/2010/11/AuthorizationContract/IsTokenValid", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MessageBase))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="IsTokenValidResponse")]
        ETL.ServicesWeb.Authentification.IsTokenValidResponse1 IsTokenValid(ETL.ServicesWeb.Authentification.IsTokenValidRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://astus.com/service/2010/11/AuthorizationContract/IsTokenValid", ReplyAction="*")]
        System.Threading.Tasks.Task<ETL.ServicesWeb.Authentification.IsTokenValidResponse1> IsTokenValidAsync(ETL.ServicesWeb.Authentification.IsTokenValidRequest request);
        
        // CODEGEN : La génération du contrat de message depuis l'espace de noms d'une partie du message http://astus.com/service/2010/11 ne correspond pas à la valeur par défaut (http://astus.com/services/2010/11)
        [System.ServiceModel.OperationContractAttribute(Action="http://astus.com/service/2010/11/AuthorizationContract/OpenSession", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MessageBase))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="OpenSessionResponse")]
        ETL.ServicesWeb.Authentification.OpenSessionResponse1 OpenSession(ETL.ServicesWeb.Authentification.OpenSessionRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://astus.com/service/2010/11/AuthorizationContract/OpenSession", ReplyAction="*")]
        System.Threading.Tasks.Task<ETL.ServicesWeb.Authentification.OpenSessionResponse1> OpenSessionAsync(ETL.ServicesWeb.Authentification.OpenSessionRequest1 request);
        
        // CODEGEN : La génération du contrat de message depuis l'espace de noms d'une partie du message http://astus.com/service/2010/11 ne correspond pas à la valeur par défaut (http://astus.com/services/2010/11)
        [System.ServiceModel.OperationContractAttribute(Action="http://astus.com/service/2010/11/AuthorizationContract/CloseSession", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MessageBase))]
        ETL.ServicesWeb.Authentification.CloseSessionResponse CloseSession(ETL.ServicesWeb.Authentification.CloseSessionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://astus.com/service/2010/11/AuthorizationContract/CloseSession", ReplyAction="*")]
        System.Threading.Tasks.Task<ETL.ServicesWeb.Authentification.CloseSessionResponse> CloseSessionAsync(ETL.ServicesWeb.Authentification.CloseSessionRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://astus.com/service/2010/11")]
    public partial class AuthenticatedRequest : MessageBase {
        
        private Token unsafeTokenField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Token UnsafeToken {
            get {
                return this.unsafeTokenField;
            }
            set {
                this.unsafeTokenField = value;
                this.RaisePropertyChanged("UnsafeToken");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://astus.com/service/2010/11")]
    public partial class Token : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(OpenSessionResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(OpenSessionRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IsTokenValidResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AuthenticatedRequest))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://astus.com/service/2010/11")]
    public abstract partial class MessageBase : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://astus.com/service/2010/11")]
    public partial class OpenSessionResponse : MessageBase {
        
        private bool isAuthenticatedField;
        
        private Token tokenField;
        
        private int fleetOwnerIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool IsAuthenticated {
            get {
                return this.isAuthenticatedField;
            }
            set {
                this.isAuthenticatedField = value;
                this.RaisePropertyChanged("IsAuthenticated");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public Token Token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
                this.RaisePropertyChanged("Token");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int FleetOwnerID {
            get {
                return this.fleetOwnerIDField;
            }
            set {
                this.fleetOwnerIDField = value;
                this.RaisePropertyChanged("FleetOwnerID");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://astus.com/service/2010/11")]
    public partial class OpenSessionRequest : MessageBase {
        
        private string usernameField;
        
        private string passwordField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
                this.RaisePropertyChanged("Username");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("Password");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://astus.com/service/2010/11")]
    public partial class IsTokenValidResponse : MessageBase {
        
        private bool isValidField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool IsValid {
            get {
                return this.isValidField;
            }
            set {
                this.isValidField = value;
                this.RaisePropertyChanged("IsValid");
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IsTokenValid", WrapperNamespace="http://astus.com/services/2010/11", IsWrapped=true)]
    internal partial class IsTokenValidRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://astus.com/service/2010/11", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://astus.com/service/2010/11", IsNullable=true)]
        public ETL.ServicesWeb.Authentification.AuthenticatedRequest AuthenticatedRequest;
        
        public IsTokenValidRequest() {
        }
        
        public IsTokenValidRequest(ETL.ServicesWeb.Authentification.AuthenticatedRequest AuthenticatedRequest) {
            this.AuthenticatedRequest = AuthenticatedRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IsTokenValidResponse", WrapperNamespace="http://astus.com/services/2010/11", IsWrapped=true)]
    internal partial class IsTokenValidResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://astus.com/service/2010/11", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://astus.com/service/2010/11")]
        public ETL.ServicesWeb.Authentification.IsTokenValidResponse IsTokenValidResponse;
        
        public IsTokenValidResponse1() {
        }
        
        public IsTokenValidResponse1(ETL.ServicesWeb.Authentification.IsTokenValidResponse IsTokenValidResponse) {
            this.IsTokenValidResponse = IsTokenValidResponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="OpenSession", WrapperNamespace="http://astus.com/services/2010/11", IsWrapped=true)]
    internal partial class OpenSessionRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://astus.com/service/2010/11", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://astus.com/service/2010/11")]
        public ETL.ServicesWeb.Authentification.OpenSessionRequest OpenSessionRequest;
        
        public OpenSessionRequest1() {
        }
        
        public OpenSessionRequest1(ETL.ServicesWeb.Authentification.OpenSessionRequest OpenSessionRequest) {
            this.OpenSessionRequest = OpenSessionRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="OpenSessionResponse", WrapperNamespace="http://astus.com/services/2010/11", IsWrapped=true)]
    internal partial class OpenSessionResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://astus.com/service/2010/11", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://astus.com/service/2010/11")]
        public ETL.ServicesWeb.Authentification.OpenSessionResponse OpenSessionResponse;
        
        public OpenSessionResponse1() {
        }
        
        public OpenSessionResponse1(ETL.ServicesWeb.Authentification.OpenSessionResponse OpenSessionResponse) {
            this.OpenSessionResponse = OpenSessionResponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CloseSession", WrapperNamespace="http://astus.com/services/2010/11", IsWrapped=true)]
    internal partial class CloseSessionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://astus.com/service/2010/11", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://astus.com/service/2010/11", IsNullable=true)]
        public ETL.ServicesWeb.Authentification.AuthenticatedRequest AuthenticatedRequest;
        
        public CloseSessionRequest() {
        }
        
        public CloseSessionRequest(ETL.ServicesWeb.Authentification.AuthenticatedRequest AuthenticatedRequest) {
            this.AuthenticatedRequest = AuthenticatedRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CloseSessionResponse", WrapperNamespace="http://astus.com/services/2010/11", IsWrapped=true)]
    internal partial class CloseSessionResponse {
        
        public CloseSessionResponse() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    internal interface AuthorizationContractChannel : ETL.ServicesWeb.Authentification.AuthorizationContract, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    internal partial class AuthorizationContractClient : System.ServiceModel.ClientBase<ETL.ServicesWeb.Authentification.AuthorizationContract>, ETL.ServicesWeb.Authentification.AuthorizationContract {
        
        public AuthorizationContractClient() {
        }
        
        public AuthorizationContractClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AuthorizationContractClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuthorizationContractClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuthorizationContractClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ETL.ServicesWeb.Authentification.IsTokenValidResponse1 ETL.ServicesWeb.Authentification.AuthorizationContract.IsTokenValid(ETL.ServicesWeb.Authentification.IsTokenValidRequest request) {
            return base.Channel.IsTokenValid(request);
        }
        
        public ETL.ServicesWeb.Authentification.IsTokenValidResponse IsTokenValid(ETL.ServicesWeb.Authentification.AuthenticatedRequest AuthenticatedRequest) {
            ETL.ServicesWeb.Authentification.IsTokenValidRequest inValue = new ETL.ServicesWeb.Authentification.IsTokenValidRequest();
            inValue.AuthenticatedRequest = AuthenticatedRequest;
            ETL.ServicesWeb.Authentification.IsTokenValidResponse1 retVal = ((ETL.ServicesWeb.Authentification.AuthorizationContract)(this)).IsTokenValid(inValue);
            return retVal.IsTokenValidResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ETL.ServicesWeb.Authentification.IsTokenValidResponse1> ETL.ServicesWeb.Authentification.AuthorizationContract.IsTokenValidAsync(ETL.ServicesWeb.Authentification.IsTokenValidRequest request) {
            return base.Channel.IsTokenValidAsync(request);
        }
        
        public System.Threading.Tasks.Task<ETL.ServicesWeb.Authentification.IsTokenValidResponse1> IsTokenValidAsync(ETL.ServicesWeb.Authentification.AuthenticatedRequest AuthenticatedRequest) {
            ETL.ServicesWeb.Authentification.IsTokenValidRequest inValue = new ETL.ServicesWeb.Authentification.IsTokenValidRequest();
            inValue.AuthenticatedRequest = AuthenticatedRequest;
            return ((ETL.ServicesWeb.Authentification.AuthorizationContract)(this)).IsTokenValidAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ETL.ServicesWeb.Authentification.OpenSessionResponse1 ETL.ServicesWeb.Authentification.AuthorizationContract.OpenSession(ETL.ServicesWeb.Authentification.OpenSessionRequest1 request) {
            return base.Channel.OpenSession(request);
        }
        
        public ETL.ServicesWeb.Authentification.OpenSessionResponse OpenSession(ETL.ServicesWeb.Authentification.OpenSessionRequest OpenSessionRequest) {
            ETL.ServicesWeb.Authentification.OpenSessionRequest1 inValue = new ETL.ServicesWeb.Authentification.OpenSessionRequest1();
            inValue.OpenSessionRequest = OpenSessionRequest;
            ETL.ServicesWeb.Authentification.OpenSessionResponse1 retVal = ((ETL.ServicesWeb.Authentification.AuthorizationContract)(this)).OpenSession(inValue);
            return retVal.OpenSessionResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ETL.ServicesWeb.Authentification.OpenSessionResponse1> ETL.ServicesWeb.Authentification.AuthorizationContract.OpenSessionAsync(ETL.ServicesWeb.Authentification.OpenSessionRequest1 request) {
            return base.Channel.OpenSessionAsync(request);
        }
        
        public System.Threading.Tasks.Task<ETL.ServicesWeb.Authentification.OpenSessionResponse1> OpenSessionAsync(ETL.ServicesWeb.Authentification.OpenSessionRequest OpenSessionRequest) {
            ETL.ServicesWeb.Authentification.OpenSessionRequest1 inValue = new ETL.ServicesWeb.Authentification.OpenSessionRequest1();
            inValue.OpenSessionRequest = OpenSessionRequest;
            return ((ETL.ServicesWeb.Authentification.AuthorizationContract)(this)).OpenSessionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ETL.ServicesWeb.Authentification.CloseSessionResponse ETL.ServicesWeb.Authentification.AuthorizationContract.CloseSession(ETL.ServicesWeb.Authentification.CloseSessionRequest request) {
            return base.Channel.CloseSession(request);
        }
        
        public void CloseSession(ETL.ServicesWeb.Authentification.AuthenticatedRequest AuthenticatedRequest) {
            ETL.ServicesWeb.Authentification.CloseSessionRequest inValue = new ETL.ServicesWeb.Authentification.CloseSessionRequest();
            inValue.AuthenticatedRequest = AuthenticatedRequest;
            ETL.ServicesWeb.Authentification.CloseSessionResponse retVal = ((ETL.ServicesWeb.Authentification.AuthorizationContract)(this)).CloseSession(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ETL.ServicesWeb.Authentification.CloseSessionResponse> ETL.ServicesWeb.Authentification.AuthorizationContract.CloseSessionAsync(ETL.ServicesWeb.Authentification.CloseSessionRequest request) {
            return base.Channel.CloseSessionAsync(request);
        }
        
        public System.Threading.Tasks.Task<ETL.ServicesWeb.Authentification.CloseSessionResponse> CloseSessionAsync(ETL.ServicesWeb.Authentification.AuthenticatedRequest AuthenticatedRequest) {
            ETL.ServicesWeb.Authentification.CloseSessionRequest inValue = new ETL.ServicesWeb.Authentification.CloseSessionRequest();
            inValue.AuthenticatedRequest = AuthenticatedRequest;
            return ((ETL.ServicesWeb.Authentification.AuthorizationContract)(this)).CloseSessionAsync(inValue);
        }
    }
}
